### ISSUE TITLE
camera jumping

### ISSUE THREAD

**Issue by arturoc** [Entropy/Entropy#30]
The problem comes from App modifying the passed mouse arguments on drag:
https://github.com/Entropy/Entropy/blob/master/Projects/EntropyLib/src/entropy/util/App.cpp#L520-L534

The arguments passed from an event should never be modified since it can have effects like this on other parts of the application which are really hard to debug.

We should have made the core events parameters const in OF but since we didn't do it from the beginning it's hard to change it now.

Anyway, not sure if that code is trying to do something else so haven't changed it but just making a copy of the ofMouseEventArgs before modifying them should fix it

**Comment by prisonerjohn** [comment]
Hey, that solves the issue with the mouse going off screen but there's still another camera jumping issue. I thought they were related but maybe not...
Steps to reproduce:
1. Open the Base parameters, you'll see controls for the Back and Front camera.
2. Make sure the Front camera is `Attached to Back` and that the Back Camera has `Mouse Control`.
3. Move the mouse around in the Back canvas to translate and rotate both cameras.
4. Uncheck Front `Attached to Back` and give the Front Camera `Mouse Control`. The view will not change as we're maintaining the global transform.
5. Try moving the mouse around in the Front canvas, and it will just jump to some unexpected position.

Let me know if that's unclear and I can probably make a video.

**Comment by prisonerjohn** [comment]
Related to #20
